xibosignage/xibo-manual

source/en/faq_webbrowser_emulation.md, source/en/layouts_designer.md
Probably the most important change to the manual ever.
=> Updated links

source/en/media_module_powerpoint.md
Added the option of PDF as an alternative way to display powerpoint,
=> additional option added to powerpoint page

source/en/media_module_subplaylist.md
edit tag for correct tip formatting
=> edit misplaced tag

source/en/displays.md, source/en/tour_two_factor_authentication.md, source/en/users_notifications.md
=> Version2 tips included

source/en/displays_metrics.md, source/en/layouts.md, source/en/layouts_designer.md, source/en/layouts_tools.md, source/en/media_module_localvideo.md, source/en/media_module_video_in.md, source/en/scheduling_dayparting.md, source/en/scheduling_events.md, source/en/tour_navigation.md, source/en/tour_two_factor_authentication.md, source/en/tour_user_profile.md, source/en/users_administration.md
Video In now includes Tizen
updated and amended links
=> Updated and amended links

source/en/displays_metrics.md, source/en/users_permissions.md
Displays link fixed on metrics page
=> broken link fix

source/en/layouts_interrupt.md, source/en/troubleshooting.md, source/en/users_notifications.md
removed duplicates and format issues, added linux to troubleshoot page
=> Minor tweaks to manual - added linux troubleshooting

source/en/layouts_interrupt.md, source/en/scheduling.md, source/en/scheduling_events.md
added player support for android for relevant manual pages
=> android support for interrupt layout added

source/en/tour_two_factor_authentication.md
=> correction for GA link

source/en/layouts_timeline.md, source/en/layouts_timeline_2.0.md, source/en/layouts_tools.md
=> v2 manual link corrected

source/en/media_module_weather.md
Outdated information removed from the user manual
=> Removed Custom Icon option from weather module

source/en/displays_settings.md, source/en/layouts_interactive_actions.md
Added info for Android setting to Display Settings and Interactive pages
=> Added touch capabilities setting for Android

source/en/displays_settings.md, source/en/layouts_interrupt.md, source/en/media_module_weather.md
=> Tizen support interrupt layouts

source/en/media_module_video_in.md
=> Video In note

source/en/media_module_weather_tiles.md
Currently not available on request as previously stated
=> Updated note for Cloud re: weather tiles

source/en/scheduling_events.md
Updated link to Interrupts page
=> Included link

source/en/media_module_video_in.md
Support for Philips for Video in from next release
=> Updated Video In

source/en/tour_two_factor_authentication.md
=> Added tip to 2fa

source/en/media_module_powerpoint.md
Powerpoint note added, deleting multiple copies
=> Update Powerpoint page

source/en/media_module_image.md, source/en/media_module_powerpoint.md, source/en/media_module_video.md, source/en/media_module_weather.md
Corrections to Modules section of manual
=> 3.1 Module edits

source/en/layouts.md, source/en/layouts_library_search.md, source/en/layouts_timeline.md, source/en/media_library.md, source/en/media_module_agenda.md, source/en/tour_guides.md
=> Spelling correction

source/en/layouts.md, source/en/layouts_library_search.md
=> enable connectors when upgrading

source/en/layouts_interrupt.md
=> Update info interrupts

source/en/media_module_powerpoint.md
=> Tip added to PPT

source/en/media_module_calendar.md, source/en/media_module_calendar_3.md, source/en/media_module_weather_3.md
=> Calendar tip added

source/en/layouts_interactive_actions.md, source/en/layouts_interactive_actions_3.md, source/en/media_module_shellcommand.md
Following release, actions now supported
=> webOS support actions

source/en/media_library.md
Added tip regarding support for expiry dates for Linux player
=> Added tip expiry dates

source/en/displays.md, source/en/displays_2.md, source/en/displays_command_functionality.md, source/en/displays_command_functionality_1.8_2.md, source/en/displays_metrics_2.md, source/en/index.md, source/en/layouts_interactive_actions.md
=> Edits to links

source/en/layouts_timeline.md, source/en/media_module_webpage.md
Webpage widget page trigger for open natively
=> Updated info

source/en/media_module_spacer.md
=> Test tagging Spacer widget

source/en/media_module_spacer.md
Revert changes for feat and version tagging
=> Revert changes for tagging

source/en/media_module_agenda.md
=> Testing format

source/en/media_module_powerpoint.md, source/en/media_module_powerpoint_2.md, source/en/media_module_shellcommand.md, source/en/media_module_twitter.md, source/en/media_module_weather.md, source/en/media_module_world_clock.md
=> Edits pages with tags

source/en/media_module_audio.md, source/en/media_module_powerpoint.md, source/en/media_module_powerpoint_2.md, source/en/media_module_shellcommand.md, source/en/media_module_twitter.md, source/en/media_module_weather.md, source/en/media_module_world_clock.md
=> edits to {feat} tags

source/en/media_modules.md
=> Feature Category table added

README.md, source/en/media_modules.md
=> feat cat table added

source/en/media_module_dashboard.md
=> added note dashboards

source/en/displays.md, source/en/displays_command_functionality.md, source/en/displays_fileassociations.md, source/en/displays_groups.md, source/en/displays_metrics.md, source/en/displays_settings.md, source/en/layouts_library_search.md, source/en/media_module_webpage.md, source/en/media_playlists.md, source/en/scheduling.md, source/en/scheduling_calendar.md, source/en/scheduling_dayparting.md, source/en/scheduling_events.md, source/en/scheduling_geolocation.md, source/en/tour_status_dashboard.md
Added feat tags for player support for display and schedule sections
=> Updated player support tags

source/en/media_module_dashboard.md
Tip included for power bi date format
=> Added note date format

source/en/layouts_interactive_actions.md
=> Corrected link

source/en/media_module_webpage.md
=> Updated link

source/en/media_datasets.md
=> Added links

source/en/displays_command_functionality.md
=> Commands update

source/en/layouts_designer.md
Tip added to Layout Designer page for Start and end dates for clarity
=> Start date tip

source/en/layouts.md
Updated to provide a suitable link from a blog
=> Updated to provide a link

source/en/displays.md
=> fix broken link

source/en/displays_settings.md
=> Edit display profile page

source/en/media.md, source/en/media_datasets.md, source/en/media_library.md
=> Minor edits

help-links.yaml, source/en/displays.md, source/en/tour_cms_settings.md, source/en/tour_tags.md, source/en/users_dashboards.md
=> Help links and additions for 4.0.2 release

help-links.yaml
=> Tweaks made to helplinks

source/en/displays.md, source/en/index.md, source/en/layouts_editor.md, source/en/media_library.md, source/en/media_menuboards.md, source/en/media_module_calendar.md, source/en/media_module_dataset.md, source/en/media_module_mastadon.md, source/en/media_module_playlist.md, source/en/media_modules.md, source/en/media_playlists.md, source/en/scheduling_events.md, source/en/tour_cms_navigation.md, source/en/tour_user_access.md, source/en/users_administration.md, source/en/users_dashboards.md
Redirects for deleted v3 pages
=> Added alias info

source/en/displays.md, source/en/media_module_menuboards_category.md, source/en/media_module_weather.md, source/en/troubleshooting.md
Added link to troubleshoot page / tweaked wording for Menu boards Categories widget.
=> Added report fault guide

source/en/media_datasets.md, source/en/media_module_weather.md, source/en/scheduling.md
=> Edits to v3 user manual

source/en/media_module_video_in.md
clarified support android 8 only
=> Updated info for Philips

source/en/layouts_editor.md
Added New Config options and editing groups
=> Additions to Data Elements

source/en/scheduling_events.md
=> Playlist url edit

source/en/media_modules.md, source/en/tour_cms_settings.md
=> Include font note

manualgenerator.class.php, source/en/displays.md, source/en/displays_metrics.md, source/en/displays_settings.md, source/en/layouts_editor.md, source/en/media_library.md, source/en/tour_cms_navigation.md
Edited image \ to / and added php to strip revision tagging for manuals
=> Image url edits and added php

manualgenerator.class.php, source/en/media_module_mastodon.md, source/en/toc/widgets.md
mastodon page url edit and php edit to strip revisions
=> Further edits to php and mastodon

source/en/layouts_editor.md, source/en/media_datasets.md, source/en/media_menuboards.md
=> Links to guides added

source/en/media_module_weather.md
Added note and link to transfer to one call 3.0
=> Added note for API 2.5

source/en/layouts_editor.md, source/en/layouts_editor_playlists.md
=> Edits to broken tag

source/en/layouts_ad_campaigns.md, source/en/layouts_campaigns.md, source/en/layouts_editor.md, source/en/layouts_editor_data_widgets.md, source/en/layouts_editor_global_elements.md, source/en/layouts_editor_library_search.md, source/en/layouts_editor_playlists.md, source/en/layouts_editor_publish_options.md, source/en/layouts_editor_widgets.md, source/en/media_modules.md, source/en/media_modules_connectors.md, source/en/toc/widgets.md
Video urls and other edits for 4.1 release
=> Videos added to pages 

source/en/layouts.md, source/en/layouts_editor_global_elements.md, source/en/layouts_editor_library_search.md, source/en/layouts_editor_widgets.md
issues with final edits in canva, new urls to replace existing.
=> video urls changed

source/en/layouts_editor_widgets.md
=> Missing character from url

source/en/displays_sync_groups.md
re linked to updated playlist page
=> link update sync groups

source/en/displays_sync_groups.md, source/en/layouts_editor_widgets.md
=> Updated link sync groups

source/en/displays_sync_groups.md, source/en/users_notifications.md
=> Edit to header tag

source/en/toc/widgets.md
=> edit to toc

source/en/using_library_searches.md
=> Update header error

source/en/using_library_searches.md
=> fixed tagging issue

source/en/what_is_a_display.md
=> incorrect tag

help-links.yaml, source/en/toc/getting_started.md
=> Edits to help links doc
